# Generated by Django 5.0.3 on 2024-03-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0002_alter_student_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=25),
        ),
    ]
